import json

labels = [
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "Lập hệ phương trình",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "tỉ lệ phần trăm",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",
    "phương trình",

]

with open('labels.json', 'w', encoding='utf-8') as f:
    json.dump(labels, f, ensure_ascii=False)
